package org.apache.jsp.jsp.dataentry;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dataEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _jspx_tagPool_s_url_value_nobody;
  private org.apache.jasper.runtime.TagHandlerPool _jspx_tagPool_s_form_theme_method_action;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _jspx_tagPool_s_url_value_nobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _jspx_tagPool_s_form_theme_method_action = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _jspx_tagPool_s_url_value_nobody.release();
    _jspx_tagPool_s_form_theme_method_action.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("   <head>\n");
      out.write("       <script>\n");
      out.write("       /**\n");
      out.write("        *  We call the function in the head tag so that it will be executed immediately,\n");
      out.write("        *  before the DOM is even parsed. Futhermore the function is fully synchronous.\n");
      out.write("        *   \n");
      out.write("        * Be sure a database is selected, otherwise it will redirect to\n");
      out.write("        * the doSelectDatabase action \n");
      out.write("        */\n");
      out.write("          \n");
      out.write("         ModUtils.checkDatabaseSelected();\n");
      out.write("      </script>\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("      <meta name=\"currentPage\" content=\"DataEntry\"/>\n");
      out.write("      <title>J-ISIS Data Entry</title>\n");
      out.write("\n");
      out.write("<!--      <link href=\"");
      if (_jspx_meth_s_url_0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\n");
      out.write("      <link href=\"");
      if (_jspx_meth_s_url_1(_jspx_page_context))
        return;
      out.write("\"  rel=\"stylesheet\" type=\"text/css\" media=\"screen\"  />-->\n");
      out.write("\n");
      out.write("      ");
      out.write("\n");
      out.write("     ");
      out.write("\n");
      out.write("      <style>\n");
      out.write("         .input-xs {\n");
      out.write("              height: 22px;\n");
      out.write("              padding: 5px 5px;\n");
      out.write("              font-size: 12px;\n");
      out.write("              line-height: 1.5;\n");
      out.write("              border-radius: 3px;\n");
      out.write("            }\n");
      out.write("         .input-group-xs>.form-control,\n");
      out.write("         .input-group-xs>.input-group-addon,\n");
      out.write("         .input-group-xs>.input-group-btn>.btn {\n");
      out.write("            height: 22px;\n");
      out.write("            padding: 1px 5px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            line-height: 1.5;\n");
      out.write("           }\n");
      out.write("      </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("         var lastSel;\n");
      out.write("         $().ready(function() {\n");
      out.write("            \n");
      out.write("            $(\"#list\").jqGrid({\n");
      out.write("                scrollrows : true,\n");
      out.write("               //url from wich data should be requested\n");
      out.write("               url:'jisis/dataentry/doDataEntryGrid.action',\n");
      out.write("               //url for edit operation\n");
      out.write("               //editurl: 'jisis/dataentry/doDataEntryEdit.action',\n");
      out.write("               datatype: 'xml',\n");
      out.write("               mtype: 'GET',\n");
      out.write("               colNames:['Label','Tag', 'Ind','Data'],\n");
      out.write("               colModel :[\n");
      out.write("                  {name:'Label', editable:false, sortable:false, index:'label', width:200, align:'right'},\n");
      out.write("                  {name:'Tag', editable:false, sortable:false, index:'tag', width:50, align:'right'},\n");
      out.write("                  {name:'Ind', editable:true, sortable:false, index:'ind',  editoptions: { size: 2 },width:50, align:'right'},\n");
      out.write("                  {name:'Data', index:'data', width:500, align:'left', sortable:false,\n");
      out.write("                     editable:true, edittype:'textarea',\n");
      out.write("                     editoptions:{rows:\"5\",cols:\"75\"} }\n");
      out.write("\n");
      out.write("\n");
      out.write("               ],\n");
      out.write("               ");
      out.write("\n");
      out.write("               rowNum: -1,\n");
      out.write("              ");
      out.write("\n");
      out.write("               // If set to clientArray, the data is not posted to the server\n");
      out.write("               // but is saved only to the grid\n");
      out.write("              ");
      out.write("\n");
      out.write("               \n");
      out.write("              cellEdit: true,\n");
      out.write("              cellsubmit: 'clientArray',\n");
      out.write("\n");
      out.write("               ");
      out.write("\n");
      out.write("               rowList:[10,20,30],\n");
      out.write("//               sortname: 'id',\n");
      out.write("//               sortorder: \"desc\",\n");
      out.write("\n");
      out.write("               //we want to display total records count\n");
      out.write("               viewrecords: true,\n");
      out.write("               //grid width\n");
      out.write("               width: 'auto',\n");
      out.write("               //grid height if 'auto' we loose the scrollbar\n");
      out.write("               height: 450,\n");
      out.write("               loadonce: false,\n");
      out.write("               imgpath: 'themes/basic/images',\n");
      out.write("               caption: 'J-ISIS Data Entry'  });\n");
      out.write("         });\n");
      out.write("         function checksave(result) {\n");
      out.write("            if(result.responseText!='') alert(result.responseText);\n");
      out.write("            else $(\"#list1\").trigger(\"reloadGrid\");\n");
      out.write("         }\n");
      out.write("\n");
      out.write("      </script>\n");
      out.write("      <style type=\"text/css\">\n");
      out.write("         #toolbar {\n");
      out.write("            padding: 10px 4px;\n");
      out.write("         }\n");
      out.write("      </style>\n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("         $(function() {\n");
      out.write("            \n");
      out.write("//             $('wksSelect').ready(function() {     \n");
      out.write("//           alert(\"doGetWorksheetNames\");\n");
      out.write("//            });\n");
      out.write("             // assign a change function to the input field\n");
      out.write("             $('#mfn').change(function() {\n");
      out.write("               // Get record from server when the input field value change\n");
      out.write("               \n");
      out.write("               getRecord(\"get\");\n");
      out.write("             });\n");
      out.write("            \n");
      out.write("            // FIRST RECORD\n");
      out.write("            $('button#first').click(function() {\n");
      out.write("\n");
      out.write("               getRecord(\"first\")\n");
      out.write("            });\n");
      out.write("            // PREVIOUS RECORD\n");
      out.write("            $('#prev').click(function() {\n");
      out.write("        \n");
      out.write("               getRecord(\"prev\");\n");
      out.write("                    \n");
      out.write("            });\n");
      out.write("            // NEXT RECORD\n");
      out.write("            $('#next').click(function() {\n");
      out.write("\n");
      out.write("               getRecord(\"next\");\n");
      out.write("            });\n");
      out.write("            // LAST RECORD\n");
      out.write("            $('button#last').click(function() {\n");
      out.write("\n");
      out.write("               getRecord(\"last\");\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // NEW RECORD\n");
      out.write("            $('button#new').click(function() {\n");
      out.write("               newRecord();\n");
      out.write("            });\n");
      out.write("            // ADD OCCURRENCE\n");
      out.write("            $('button#addoccurrence').click(function() {\n");
      out.write("\n");
      out.write("               var id = $(\"#list\").getGridParam(\"selrow\");\n");
      out.write("               //alert(\" id=\"+id);\n");
      out.write("               var ids = jQuery(\"#list\").jqGrid('getDataIDs');\n");
      out.write("               //alert(\" ids=\"+ids);\n");
      out.write("               var newId =ids.length;\n");
      out.write("\n");
      out.write("               if (id) {\n");
      out.write("                  var ret = $(\"#list\").jqGrid('getRowData',id);\n");
      out.write("                  //alert(\" tag=\"+ret['Tag']);\n");
      out.write("                  var datarow = {Label: ret['Label'], Tag: ret['Tag'], Ind: \"\", Data: \"\"};\n");
      out.write("                  \n");
      out.write("                  //alert(\"newId=\"+newId+datarow['Label']+datarow['Tag']);\n");
      out.write("                  var su=jQuery(\"#list\").jqGrid('addRowData',newId,datarow,\"after\",id);\n");
      out.write("\n");
      out.write("                 \n");
      out.write("                  //alert(\"success=\"+su);\n");
      out.write("                  if(su) {\n");
      out.write("                     var tableData = new Array();\n");
      out.write("                     var ids = $(\"#list\").getDataIDs();\n");
      out.write("                     var selId = id;\n");
      out.write("                      //alert(\"ids=\"+ids);\n");
      out.write("                      for(var i = 0; i < ids.length; i++){\n");
      out.write("                         tableData[i] = $(\"#list\").getRowData(ids[i]);\n");
      out.write("                         if (ids[i] == id) {\n");
      out.write("                            selId = i+1;\n");
      out.write("                         }\n");
      out.write("                         tableData[i].id = i ;\n");
      out.write("                      }\n");
      out.write("                      $(\"#list\").clearGridData(false);\n");
      out.write("                      for(i = 0; i < tableData.length; i++){\n");
      out.write("                         $(\"#list\").addRowData(i, tableData[i]);\n");
      out.write("                      }\n");
      out.write("                      jQuery(\"#list\").resetSelection();\n");
      out.write("                      jQuery(\"#list\").setSelection(selId)\n");
      out.write("                   }\n");
      out.write("                  else { alert(\"Row not inserted!\")};\n");
      out.write("                  \n");
      out.write("               } else {\n");
      out.write("                  alert(\"Please select row\");}\n");
      out.write("               \n");
      out.write("            });\n");
      out.write("            // DELETE OCCURRENCE/FIELD\n");
      out.write("            $('button#deloccurrence').click(function() {\n");
      out.write("              \n");
      out.write("               var id = $(\"#list\").getGridParam(\"selrow\");\n");
      out.write("               \n");
      out.write("               if (id) {\n");
      out.write("                   deleteRow();\n");
      out.write("\n");
      out.write("               }\n");
      out.write("\n");
      out.write("               });\n");
      out.write("            // DELETE RECORD\n");
      out.write("            $('button#delete').click(function() {\n");
      out.write("               //Delete icon clicked\n");
      out.write("               confirmDelete(\n");
      out.write("                  function(result){\n");
      out.write("                     if (result == true) {\n");
      out.write("                        $.get('jisis/dataentry/doDeleteRecord.action',\n");
      out.write("                              {mfn: $(\"#mfn\").val(), oper: \"delete\", type: \"results\"},\n");
      out.write("                              function(serverMsg){\n");
      out.write("                                 alert(serverMsg);\n");
      out.write("                                 getRecord(\"prev\");\n");
      out.write("                              }\n");
      out.write("                        );\n");
      out.write("                     }\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            // SAVE RECORD DATA\n");
      out.write("            $('button#save').click(function() {\n");
      out.write("               // Send the Grid data to the server\n");
      out.write("            \n");
      out.write("               var data = getData();\n");
      out.write("                   \n");
      out.write("\n");
      out.write("               //alert(\"data=\"+data);\n");
      out.write("               $.post('jisis/dataentry/doSaveRecord.action',\n");
      out.write("               \n");
      out.write("               {recordData: data, type: \"results\"},\n");
      out.write("\n");
      out.write("               function(mfn) {\n");
      out.write("                     $(\"#mfn\").val(mfn);\n");
      out.write("                     alert(\"New Data Successfully Saved - Record with MFN: \"+mfn);\n");
      out.write("               })\n");
      out.write("               \n");
      out.write("            });\n");
      out.write("\n");
      out.write("            function getData(){\n");
      out.write("               // Get all rows\n");
      out.write("               var rows  = $(\"#list\").jqGrid('getRowData');\n");
      out.write("               var xml = \"<Record>\\n\";\n");
      out.write("               for(var i=0;i < rows.length; i++){\n");
      out.write("                  var row = rows[i];\n");
      out.write("                  xml += \"<Field tag=\\\"\"+row['Tag']+\"\\\">\"+row['Data']+\"</Field>\\n\";\n");
      out.write("                 \n");
      out.write("               }\n");
      out.write("               xml += \"</Record>\";\n");
      out.write("               return xml;\n");
      out.write("            };\n");
      out.write("            \n");
      out.write("            $('#gotomfn').click(function(){\n");
      out.write("\n");
      out.write("               getRecord(\"get\");\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            function getRecord(oper)\t{\n");
      out.write("\n");
      out.write("               $.get('jisis/dataentry/doGet.action',\n");
      out.write("               {mfn: $(\"#mfn\").val(), oper: oper, type: \"results\"}, function(data){\n");
      out.write("                  var mygrid = $(\"#list\")[0];\n");
      out.write("                  mygrid.addXmlData(data);\n");
      out.write("                  $.get('jisis/dataentry/doGetMfn.action',\n");
      out.write("                  {type: \"results\"},\n");
      out.write("                  function(mfn) {\n");
      out.write("                     $(\"#mfn\").val(mfn);\n");
      out.write("                  })\n");
      out.write("                 \n");
      out.write("                  \n");
      out.write("               });\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function newRecord()\t{\n");
      out.write("\n");
      out.write("\n");
      out.write("               $.get('jisis/dataentry/doDataEntryGrid.action',\n");
      out.write("               {mfn: $(\"#mfn\").val(), type: \"results\"},\n");
      out.write("               function(data){\n");
      out.write("\n");
      out.write("                  var mygrid = $(\"#list\")[0];\n");
      out.write("                  mygrid.addXmlData(data);\n");
      out.write("               });\n");
      out.write("\n");
      out.write("               $(\"#mfn\").val(\"0\");\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function confirmDelete(callback){\n");
      out.write("               // jQuery UI Dialog\n");
      out.write("               var $dialog = $('<div></div>')\n");
      out.write("\t\t.html('<p><span class=\"ui-icon ui-icon-alert\" style=\"color:red; float:left; margin:0 7px 0 0;\"></span>'\n");
      out.write("                      + '<p><span class=\"ui-dialog-content\">You clicked on Delete icon !</p>'\n");
      out.write("                      + '<p>This record will be permanently deleted and cannot be recovered. Are you sure?</p>'\n");
      out.write("                      + '<p>If this is correct, click Delete Record.</p><p>To cancel, click Cancel.<p>')\n");
      out.write("\t\t.dialog({\n");
      out.write("\t\t\tautoOpen: false,\n");
      out.write("\t\t\ttitle: 'Do you really want to delete this record!',\n");
      out.write("                        width: 400,\n");
      out.write("                  modal: true,\n");
      out.write("                  resizable: false,\n");
      out.write("                  buttons: {\n");
      out.write("                     \"Delete Record\": function() {\n");
      out.write("                        $(this).dialog(\"close\");\n");
      out.write("                        callback(true);\n");
      out.write("                     },\n");
      out.write("                     \"Cancel\": function() {\n");
      out.write("                        $(this).dialog(\"close\");\n");
      out.write("                        callback(false);\n");
      out.write("                     }\n");
      out.write("                  }\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("                $dialog.dialog('open');\n");
      out.write("\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function deleteRow(){\n");
      out.write("              var tableData = new Array();\n");
      out.write("              var ids = '';\n");
      out.write("              var su = $(\"#list\").delRowData($(\"#list\").getGridParam('selrow'));\n");
      out.write("//              alert(\"su=\"+su);\n");
      out.write("              ids = $(\"#list\").getDataIDs();\n");
      out.write("              //alert(\"ids=\"+ids);\n");
      out.write("              for(var i = 0; i < ids.length; i++){\n");
      out.write("                 tableData[i] = $(\"#list\").getRowData(ids[i]);\n");
      out.write("                 tableData[i].id = i ;\n");
      out.write("              }\n");
      out.write("              $(\"#list\").clearGridData(false);\n");
      out.write("              for(i = 0; i < tableData.length; i++){\n");
      out.write("                 $(\"#list\").addRowData(i, tableData[i]);\n");
      out.write("              }\n");
      out.write("              jQuery(\"#list\").resetSelection();\n");
      out.write("           }\n");
      out.write("\n");
      out.write("       });\n");
      out.write("\n");
      out.write("      </script>\n");
      out.write("               \n");
      out.write("\n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("         //---------------------------------------------------------------------\n");
      out.write("         // Code to set the WKS selection field in the navigation toolbar and to\n");
      out.write("         //  respond on change events\n");
      out.write("         //---------------------------------------------------------------------\n");
      out.write("         // When the document is ready, run the function\n");
      out.write("         // shortcut for document-ready idiom\n");
      out.write("         $(function() {\n");
      out.write("            $(\"#wksSelect\").ready(function() {\n");
      out.write("               // GET request\n");
      out.write("               $.get('jisis/dataentry/doGetWorksheetNames.action',\n");
      out.write("               {type: \"results\"},\n");
      out.write("               // The callback will be passed the response data and status\n");
      out.write("               function(options) {\n");
      out.write("                  \n");
      out.write("                 // We get back the list of pftNames in options\n");
      out.write("                 $('#wksSelect').replaceWith(options);\n");
      out.write("                 // Set the function to be called when there is a change\n");
      out.write("                 //$('select#wksSelect').change(onSelectChange);\n");
      out.write("                  $('#wksSelect').select2({\n");
      out.write("                       formatResult: format,\n");
      out.write("                       formatSelection: format\n");
      out.write("                  })                 \n");
      out.write("                     .on(\"change\", function(e) {\n");
      out.write("                        //fired when WKS value changes  \n");
      out.write("                        //alert(\"Change WKS \"+e.val)\n");
      out.write("                        changeWks(e.val);\n");
      out.write("                     });\n");
      out.write("               });\n");
      out.write("            });\n");
      out.write("         });\n");
      out.write("         \n");
      out.write("         function format(item) {\n");
      out.write("             var originalText = item.text;\n");
      out.write("             return \"<div style=\\\"text-align:left\\\">\" + originalText + \"</div>\";\n");
      out.write("         }\n");
      out.write("\n");
      out.write("            \n");
      out.write("           \n");
      out.write("\n");
      out.write("            function changeWks(wksName){\n");
      out.write("               //alert(\"changePft function \");\n");
      out.write("           // Change the WKS on the Server side\n");
      out.write("           $.get('jisis/dataentry/doChangeWks.action',\n");
      out.write("              {wksName: wksName},\n");
      out.write("              function(){\n");
      out.write("                 //alert('doChangeWks callback');\n");
      out.write("                 // Get the record formatted with the new WKS\n");
      out.write("                 //alert('mfn id'+$(\"#mfn\").length + ' element');\n");
      out.write("                 var mfnValue = $(\"#mfn\").val();\n");
      out.write("                 if (mfnValue.length == 0) { mfnValue = \"0\";}\n");
      out.write("\n");
      out.write("                  $.get('jisis/dataentry/doGet.action',\n");
      out.write("                    {mfn: mfnValue, oper: \"get\", type: \"results\"}, \n");
      out.write("                    function(data){\n");
      out.write("                     //alert('doGet callback');\n");
      out.write("                      var mygrid = $(\"#list\")[0];\n");
      out.write("                      mygrid.addXmlData(data);\n");
      out.write("                      $.get('jisis/dataentry/doGetMfn.action',\n");
      out.write("                       {type: \"results\"},\n");
      out.write("                        function(mfn) {\n");
      out.write("                           \n");
      out.write("                           //alert('doGetMfn callback');\n");
      out.write("                           $(\"#mfn\").val(mfn);\n");
      out.write("                      });\n");
      out.write("\n");
      out.write("                   });\n");
      out.write("           });\n");
      out.write("              \n");
      out.write("            }\n");
      out.write("         \n");
      out.write("      </script>\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      \n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"browse-navbar-collapse\">\n");
      out.write("         <div class=\"navbar navbar-default\" role=\"navigation\">  \n");
      out.write("            <div class=\"navbar-inner\">  \n");
      out.write("               <div class=\"container\">  \n");
      out.write("                  \n");
      out.write("                    \n");
      out.write("                  <!--navigation does here--> \n");
      out.write("                \n");
      out.write("                 <div class=\"row\">\n");
      out.write("                  <div class=\"col-lg-2\">\n");
      out.write("\n");
      out.write("                     <div class=\"input-group\">\n");
      out.write("\n");
      out.write("                        <input type=\"text\"  id=\"mfn\" class=\"form-control   input-xs\" placeholder=\"Enter MFN\">\n");
      out.write("\n");
      out.write("                        <span class=\"input-group-btn\">\n");
      out.write("                           <button type=\"button\" id=\"gotomfn\" class=\"btn  btn-xs\">Go!</button>\n");
      out.write("                        </span>\n");
      out.write("\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("<!--                   <h6><span class=\"label label-default\">MFN</span></h6>\n");
      out.write("                   <input type=\"text\" size=\"8\" id=\"mfn\" />\n");
      out.write("                   \n");
      out.write("                  \n");
      out.write("                   <button type=\"button\" class=\"btn btn-default navbar-btn btn-xs\" id=\"gotomfn\">Go</button>\n");
      out.write("                  -->\n");
      out.write("              \n");
      out.write("                  <button  type=\"button\" title=\"First Record\"      class=\"btn btn-default navbar-btn btn-xs\" id=\"first\" title=\"First Record\"><span class=\"glyphicon glyphicon-step-backward\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Previous Record\"   class=\"btn btn-default navbar-btn btn-xs\" id=\"prev\" title=\"Previous Record\"><span class=\"glyphicon glyphicon-chevron-left\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Next Record\"       class=\"btn btn-default navbar-btn btn-xs\" id=\"next\" title=\"Next Record\"><span class=\"glyphicon glyphicon-chevron-right\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Last Record\"       class=\"btn btn-default navbar-btn btn-xs\" id=\"last\" title=\"Last Record\"><span class=\"glyphicon glyphicon-step-forward\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"New Record\"        class=\"btn btn-default navbar-btn btn-xs\" id=\"new\"><span class=\"glyphicon glyphicon-plus\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Delete Rrecord\"    class=\"btn btn-default navbar-btn btn-xs\" id=\"delete\"><span class=\"glyphicon glyphicon-remove\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Save Record\"       class=\"btn btn-default navbar-btn btn-xs\" id=\"save\"><span class=\"glyphicon glyphicon-floppy-save\"></span></button>\n");
      out.write("                  <button  type=\"button\" title =\"Add Occurrence\"   class=\"btn btn-default navbar-btn btn-xs\" id=\"addoccurrence\"><span class=\"glyphicon glyphicon-plus-sign\"></span></button>\n");
      out.write("                  <button  type=\"button\" title=\"Delete Occurrence\" class=\"btn btn-default navbar-btn btn-xs\" id=\"deloccurrence\"><span class=\"glyphicon glyphicon-minus-sign\"></button>\n");
      out.write("                   \n");
      out.write("                   <span class=\"label label-default\">WKS:</span><select id=\"wksSelect\"></select>\n");
      out.write("                   \n");
      out.write("               </div>  \n");
      out.write("            </div>  \n");
      out.write("         </div>  \n");
      out.write("        </div>    \n");
      out.write("\n");
      out.write("      <br>&nbsp;<br>\n");
      out.write("      ");
      if (_jspx_meth_s_form_0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("         \n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_url_0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_url_0 = (org.apache.struts2.views.jsp.URLTag) _jspx_tagPool_s_url_value_nobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_url_0.setPageContext(_jspx_page_context);
    _jspx_th_s_url_0.setParent(null);
    _jspx_th_s_url_0.setValue("scripts/jquery.jqGrid-4.6.0/css/ui.jqgrid.css");
    int _jspx_eval_s_url_0 = _jspx_th_s_url_0.doStartTag();
    if (_jspx_th_s_url_0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return true;
    _jspx_tagPool_s_url_value_nobody.reuse(_jspx_th_s_url_0);
    return false;
  }

  private boolean _jspx_meth_s_url_1(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_url_1 = (org.apache.struts2.views.jsp.URLTag) _jspx_tagPool_s_url_value_nobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_url_1.setPageContext(_jspx_page_context);
    _jspx_th_s_url_1.setParent(null);
    _jspx_th_s_url_1.setValue("scripts/jquery-ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.css");
    int _jspx_eval_s_url_1 = _jspx_th_s_url_1.doStartTag();
    if (_jspx_th_s_url_1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return true;
    _jspx_tagPool_s_url_value_nobody.reuse(_jspx_th_s_url_1);
    return false;
  }

  private boolean _jspx_meth_s_form_0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_form_0 = (org.apache.struts2.views.jsp.ui.FormTag) _jspx_tagPool_s_form_theme_method_action.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_form_0.setPageContext(_jspx_page_context);
    _jspx_th_s_form_0.setParent(null);
    _jspx_th_s_form_0.setAction("doDataEntry");
    _jspx_th_s_form_0.setMethod("POST");
    _jspx_th_s_form_0.setTheme("simple");
    int _jspx_eval_s_form_0 = _jspx_th_s_form_0.doStartTag();
    if (_jspx_eval_s_form_0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_form_0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_form_0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_form_0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\n");
        out.write("         <table id=\"list\" class=\"scroll\"></table>\n");
        out.write("         ");
        out.write("\n");
        out.write("\n");
        out.write("         <div id=\"pscrolling\"></div>\n");
        out.write("\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_s_form_0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_form_0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE)
        out = _jspx_page_context.popBody();
    }
    if (_jspx_th_s_form_0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
      return true;
    _jspx_tagPool_s_form_theme_method_action.reuse(_jspx_th_s_form_0);
    return false;
  }
}
