package org.apache.jsp.jsp.browseviewer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DataViewer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("   <head>\n");
      out.write("      <script>\n");
      out.write("       /**\n");
      out.write("        *  We call the function in the head tag so that it will be executed immediately,\n");
      out.write("        *  before the DOM is even parsed. Futhermore the function is fully synchronous.\n");
      out.write("        *   \n");
      out.write("        * Be sure a database is selected, otherwise it will redirect to\n");
      out.write("        * the doSelectDatabase action \n");
      out.write("        */\n");
      out.write("          \n");
      out.write("         ModUtils.checkDatabaseSelected();\n");
      out.write("      </script>\n");
      out.write("      \n");
      out.write("      <style type=\"text/css\">\n");
      out.write("         #toolbar {\n");
      out.write("            padding: 10px 4px;\n");
      out.write("         }\n");
      out.write("      </style>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("         \n");
      out.write("         $(function() {\n");
      out.write("                                     \n");
      out.write("               // AJAX calls are asynchronous\n");
      out.write("               initMfn();\n");
      out.write("                 \n");
      out.write("               $('button#first').button({\n");
      out.write("                  text: false,\n");
      out.write("                  icons: {\n");
      out.write("                     primary: 'ui-icon-seek-first'\n");
      out.write("                  }\n");
      out.write("               })\n");
      out.write("               .click(function() {\n");
      out.write("\n");
      out.write("                  getRecord(\"first\");\n");
      out.write("               });\n");
      out.write("\n");
      out.write("               $('#prev').button({\n");
      out.write("                  text: false,\n");
      out.write("                  icons: {\n");
      out.write("                     primary: 'ui-icon-seek-prev'\n");
      out.write("                  }\n");
      out.write("               })\n");
      out.write("               .click(function() {\n");
      out.write("               \n");
      out.write("                  getRecord(\"prev\");\n");
      out.write("\n");
      out.write("               });\n");
      out.write("            $('#next').button({\n");
      out.write("               text: false,\n");
      out.write("               icons: {\n");
      out.write("                  primary: 'ui-icon-seek-next'\n");
      out.write("               }\n");
      out.write("            })\n");
      out.write("             .click(function() {\n");
      out.write("\n");
      out.write("                 getRecord(\"next\");\n");
      out.write("               });\n");
      out.write("\n");
      out.write("            $('button#last').button({\n");
      out.write("               text: false,\n");
      out.write("               icons: {\n");
      out.write("                  primary: 'ui-icon-seek-end'\n");
      out.write("               }\n");
      out.write("            })\n");
      out.write("             .click(function() {\n");
      out.write("\n");
      out.write("                 getRecord(\"last\");\n");
      out.write("               });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          $('#gotomfn').button({\n");
      out.write("               text: true\n");
      out.write("\n");
      out.write("            })\n");
      out.write("           .click(function(){\n");
      out.write("\n");
      out.write("               getRecord(\"get\");\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            function getRecord(oper)\t{\n");
      out.write("               // AJAX calls are asynchronous, thus we need to embed the 2nd\n");
      out.write("               // AJAX call in the 1st callback function to be sure it is\n");
      out.write("               // processed after.\n");
      out.write("               // $ or jQuery references the glogal jQuery object (defined once\n");
      out.write("               // by the jQuery library)\n");
      out.write("               $.get('jisis/doGetRecord.action',\n");
      out.write("                      // The parameters to send\n");
      out.write("                      {mfn: $(\"#mfn\").val(), oper: oper, type: \"results\"},\n");
      out.write("                      // The callback function that process the resulting data\n");
      out.write("                      function(data){\n");
      out.write("                          // Display the record\n");
      out.write("                          $(\"div#recordDisplay\").html(data);\n");
      out.write("                          // Get the MFN from the server\n");
      out.write("                          $.get('jisis/doGetRecordMfn.action',\n");
      out.write("                               {type: \"results\"},\n");
      out.write("                               // The callback function that process the MFN\n");
      out.write("                               function(mfn) {\n");
      out.write("                                  // put the MFN in the input field\n");
      out.write("                                  $(\"#mfn\").val(mfn);\n");
      out.write("                               });\n");
      out.write("\n");
      out.write("\n");
      out.write("                     });\n");
      out.write("            }\n");
      out.write("           \n");
      out.write("\n");
      out.write("            function initMfn() {\n");
      out.write("               // Get the last MFN number from the server\n");
      out.write("               $.get('jisis/doGetLastMfn.action',\n");
      out.write("                     {type: \"results\"},\n");
      out.write("                     // callback function to process the returned last MFN     \n");
      out.write("                     function(mfn) {\n");
      out.write("                        // We define a HTML input field\n");
      out.write("                        var input = '<input type=\"number\" min=\"1\" step=\"1\"'\n");
      out.write("                             + ' max=\"' + mfn + '\" id=\"mfn\"'\n");
      out.write("                             + '/>';\n");
      out.write("                    \n");
      out.write("                       $(\"#mfn\").replaceWith(input);\n");
      out.write("                       // assign a change function to the input field\n");
      out.write("                       $('#mfn').change(function() {\n");
      out.write("                          // Get record from server when the input field value change\n");
      out.write("                          getRecord(\"get\");\n");
      out.write("                      });\n");
      out.write("                      // Input is set, now we can get the record\n");
      out.write("                      getRecord(\"first\");\n");
      out.write("                  });\n");
      out.write("\n");
      out.write("               }\n");
      out.write("            });              \n");
      out.write("      </script>\n");
      out.write("      \n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("         //---------------------------------------------------------------------\n");
      out.write("         // Code to set the PFT selection field in the navigation toolbar and to\n");
      out.write("         //  respond on change events\n");
      out.write("         //---------------------------------------------------------------------\n");
      out.write("         // When the document is ready, run the function\n");
      out.write("         // shortcut for document-ready idiom\n");
      out.write("         $(function() {\n");
      out.write("            $(\"#pftSelect\").ready(function() {\n");
      out.write("               // GET request\n");
      out.write("               $.get('jisis/doGetPftNames.action',\n");
      out.write("               {type: \"results\"},\n");
      out.write("               // The callback will be passed the response data and status\n");
      out.write("               function(options) {\n");
      out.write("                  \n");
      out.write("                 // We get back the list of pftNames in options\n");
      out.write("                 $('#pftSelect').replaceWith(options);\n");
      out.write("                 // Set the function to be called when there is a change\n");
      out.write("                 //$('select#pftSelect').change(onSelectChange);\n");
      out.write("                  $('#pftSelect').select2(\n");
      out.write("                  )                 \n");
      out.write("                     .on(\"change\", function(e) {\n");
      out.write("                        //fired when PFT value changes \n");
      out.write("                        //alert(\"change function\");\n");
      out.write("                        changePft(e.val);\n");
      out.write("                     });\n");
      out.write("               });\n");
      out.write("            });\n");
      out.write("         });\n");
      out.write("         \n");
      out.write("         function format(item) {\n");
      out.write("             var originalText = item.text;\n");
      out.write("             return \"<div style=\\\"text-align:left\\\">\" + originalText + \"</div>\";\n");
      out.write("         }\n");
      out.write("\n");
      out.write("            \n");
      out.write("           \n");
      out.write("\n");
      out.write("            function changePft(pftName){\n");
      out.write("              //alert(\"changePft function \");\n");
      out.write("              // Change the PFT on the Server side\n");
      out.write("              $.get('jisis/doChangePft.action',\n");
      out.write("                 {pftName: pftName},\n");
      out.write("                 function(){\n");
      out.write("                     \n");
      out.write("                    // Get the record formatted with the new PFT\n");
      out.write("                    $.get('jisis/doGetRecord.action',\n");
      out.write("                       {mfn: $(\"#mfn\").val(), oper: \"get\", type: \"results\"},\n");
      out.write("                       function(data){\n");
      out.write("                         // alert(\"doGetRecord function(data)\");\n");
      out.write("                          $(\"div#recordDisplay\").html(data);\n");
      out.write("                       }\n");
      out.write("                    );\n");
      out.write("                 }\n");
      out.write("              );\n");
      out.write("            }\n");
      out.write("         \n");
      out.write("      </script>\n");
      out.write("      \n");
      out.write("   </head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <body>\n");
      out.write("     \n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("         <div class=\"navbar navbar-default\" role=\"navigation\">  \n");
      out.write("           \n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("               <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#browse-navbar-collapse\">\n");
      out.write("                  <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                  <span class=\"icon-bar\"></span>\n");
      out.write("                  <span class=\"icon-bar\"></span>\n");
      out.write("                  <span class=\"icon-bar\"></span>\n");
      out.write("               </button>\n");
      out.write("                <!--results navigation bar placeholder-->\n");
      out.write("               <a class=\"navbar-brand\" href=\"#\">Browse</a>\n");
      out.write("            </div>\n");
      out.write("             <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"browse-navbar-collapse\">\n");
      out.write("               <div class=\"navbar-inner\">  \n");
      out.write("                  <div class=\"container\">  \n");
      out.write("                     <div class=\"row\">\n");
      out.write("                        <!--navigation does here--> \n");
      out.write("                        <!--Placeholder for from-to of text -->\n");
      out.write("                        <span class=\"label label-default\">MFN</span>\n");
      out.write("                        <input type=\"number\" min=\"1\" step=\"1\" id=\"mfn\" >\n");
      out.write("\n");
      out.write("                        <button  type=\"button\" class=\"btn btn-default navbar-btn btn-xs\" id=\"first\" title=\"First Record\">first</button>\n");
      out.write("                        <button  type=\"button\" class=\"btn btn-default navbar-btn btn-xs\" id=\"prev\" title=\"Previous Record\">prev</button>\n");
      out.write("                        <button  type=\"button\" class=\"btn btn-default navbar-btn btn-xs\" id=\"next\" title=\"Next Record\">next</button>\n");
      out.write("                        <button  type=\"button\" class=\"btn btn-default navbar-btn btn-xs\" id=\"last\" title=\"Last Record\">last</button>\n");
      out.write("\n");
      out.write("                        <span class=\"label label-default\">PFT:</span><select id=\"pftSelect\"></select>\n");
      out.write("                     </div> \n");
      out.write("                  </div>  \n");
      out.write("               </div>  \n");
      out.write("            </div>  \n");
      out.write("         </div> <!-- /.navbar-collapse -->\n");
      out.write("      </div>   <!-- /.container -->\n");
      out.write("\n");
      out.write("      <!--      <div class=\"well\">\n");
      out.write("               <span id=\"database\"></span>\n");
      out.write("            </div>-->\n");
      out.write("      <!--container constrains the width of the navbar contents, centers them within a wide\n");
      out.write("      screen, and includes a clearfix so that it will contain floated child elements.-->\n");
      out.write("      <div class=\"container\"> \n");
      out.write("         <div id=\"recordDisplay\">\n");
      out.write("            <p id=\"record\"></p>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("   </body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
